export const mockContents = [
  {
    _id: "1",
    title: "Introduction to Next.js",
    link: "https://www.youtube.com/watch?v=Sklc_fQBmcs",
    type: "youtube",
    description: "A comprehensive guide to getting started with Next.js framework",
    userId: "user1",
    tags: ["coding", "nextjs"],
  },
  {
    _id: "2",
    title: "React Hooks Explained",
    link: "https://www.youtube.com/watch?v=dpw9EHDh2bM",
    type: "youtube",
    description: "Deep dive into React Hooks and their practical applications",
    userId: "user1",
    tags: ["coding", "react"],
  },
  {
    _id: "3",
    title: "Interesting Twitter Thread on AI",
    link: "https://twitter.com/elonmusk/status/1234567890",
    type: "twitter",
    description: "Discussion about the future of artificial intelligence",
    userId: "user1",
    tags: ["ai", "tech"],
  },
  {
    _id: "4",
    title: "Great Article on Web Development",
    link: "https://css-tricks.com/how-to-create-a-responsive-grid-design/",
    type: "url",
    description: "Learn how to create responsive grid layouts in CSS",
    userId: "user1",
    tags: ["webdev", "css"],
  },
  {
    _id: "5",
    title: "Tailwind CSS Tutorial",
    link: "https://www.youtube.com/watch?v=UBOj6rqRUME",
    type: "youtube",
    description: "Complete tutorial on using Tailwind CSS for modern web design",
    userId: "user1",
    tags: ["css", "tailwind"],
  },
]